-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."TournamentPlayer" add column "disqualified" boolean
--  not null default 'false';
