version: 3
endpoint: https://hasura.dev.advancedtransponder.net:443
admin_secret: SuperSekritHasura
metadata_directory: metadata
actions:
  kind: synchronous
  handler_webhook_baseurl: http://matchmaker-service:80
