version: 3
endpoint: 
  from_env: HASURA_EXT_ENDPOINT
admin_secret: 
  from_env: HASURA_GRAPHQL_ADMIN_SECRET
metadata_directory: metadata
actions:
  kind: synchronous
  handler_webhook_baseurl: 
    from_env: HASURA_MATCHMAKER_URI
